---
branches:
  - main

plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/changelog'
  - '@semantic-release/npm'
  - '@semantic-release/github'
  - '@semantic-release/git'

changelogFile: CHANGELOG.md

# Automatische Commit-Nachricht für den Changelog und Versions-Updates
git:
  assets:
    - CHANGELOG.md
    - package.json
  message: 'chore(release): ${nextRelease.version} [skip ci]'
