---
name: Bug Report
description: Report a bug you found on the portfolio ✨
labels: ["kind/bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please describe the problem in as much detail as possible. If needed, I may ask follow-up questions.
        Screenshots, videos, and console logs are incredibly helpful!

  - type: textarea
    id: problem
    attributes:
      label: What happened?
      description: |
        Clearly describe what you did and what the result was.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
      description: |
        Describe what you thought should have happened instead.
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: How can we reproduce the issue?
      description: |
        A step-by-step guide is very helpful. The more precise, the better!
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll to '...'
        4. See the error
    validations:
      required: true

  - type: markdown
    attributes:
      value: '### Environment'

  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: e.g., Windows 11, macOS 14.3, Ubuntu 22.04
    validations:
      required: false

  - type: input
    id: browser
    attributes:
      label: Browser + Version
      placeholder: e.g., Chrome 123, Safari 17.3, Firefox 124
    validations:
      required: true

  - type: textarea
    id: console_logs
    attributes:
      label: Console or terminal logs
      description: Paste any relevant browser console or terminal output if available.
      placeholder: |
        [Error] Uncaught TypeError: Cannot read properties of undefined (reading '...')
        at ...
      render: shell
    validations:
      required: false

  - type: textarea
    id: screenshot
    attributes:
      label: Screenshots or Videos (optional)
      description: You can link to images or screen recordings (e.g., imgur.com, CleanShot, Loom, etc.)
      placeholder: |
        ![Screenshot](https://link.to/image)
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: Additional context or notes
      placeholder: Anything else that might help.
    validations:
      required: false